name: Build EXE

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Compile
        shell: cmd
        run: |
          cl /nologo soc_alarm_modified.c /link user32.lib gdi32.lib shell32.lib comctl32.lib winmm.lib /SUBSYSTEM:WINDOWS /OUT:SOC_Checklist_Alarm.exe

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: SOC_Checklist_Alarm
          path: |
            SOC_Checklist_Alarm.exe
            mixkit-sound-alert-in-hall-1006.wav
